# This is a basic workflow to help you get started with Actions

name: Auto Releaser

# Controls when the workflow will run
on:
  workflow_run:
    workflows: ["CI"]
    branches: [main]
    types: 
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Workflow check (success)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        run: echo "Proceeding with release 🎁"
      - name: Workflow check (failure)
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: echo "Previous workflow failed, cancelling release ❌" && exit 1

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Install semantic-release plugins
        run: npm i --no-save @semantic-release/git @semantic-release/changelog
      - uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
