name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Tests
  ci:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          repository: faster-games/package-testbed
      - uses: actions/checkout@v2
        with:
          lfs: true
          path: Packages/com.faster-games.package-template
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-TestPlatform
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: playmode_tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          testMode: playmode
          artifactsPath: playmode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Play Mode Test Results
      - uses: game-ci/unity-test-runner@v2
        id: editmode_tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          testMode: editmode
          artifactsPath: editmode-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: Edit Mode Test Results
      - name: Export .unitypackage from Unity Project
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          packagePath: Packages/com.faster-games.package-template
          outputPackagePath: dist/com.faster-games.package-template.unitypackage
      - name: Install semantic-release plugins
        if: ${{ github.ref == 'refs/heads/main' }}
        run: npm i --no-save @semantic-release/git @semantic-release/changelog
      - uses: codfish/semantic-release-action@v1
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
