name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Tests
  testAllModes:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
          repository: faster-games/package-testbed
      - uses: actions/checkout@v2
        with:
          lfs: true
          path: Packages/com.faster-games.package-template
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-TestPlatform
          restore-keys: |
            Library-
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }}-artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
  release:
    name: Release
    needs: [testAllModes]
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Export .unitypackage from Unity Project
        uses: FrostBanditTeam/extract-unity-package-action@1
        with:
          packagePath: Packages/com.faster-games.package-template
          outputPackagePath: dist/com.faster-games.package-template.unitypackage
      - name: Install semantic-release plugins
        run: npm i --no-save @semantic-release/git @semantic-release/changelog
      - uses: codfish/semantic-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
